GET http://localhost:3000/companies

###

GET http://localhost:3000/companies?search=코드잇&offset=0&limit=10&view=employeeDesc

###

GET http://localhost:3000/companies/3f89b7b2-d0e8-4d9e-bc4e-4c88709c1e76

###

POST http://localhost:3000/companies/d1f9c0a8-251e-469d-9b8c-1e6e84f1de21/comparison?view=revenueDesc
Content-Type: application/json

{
  "bodyCompanyIds" : [
    "b89d6dc9-3f0b-4c18-918e-b37c0f276fe3",
    "e7a8de0c-1583-4f84-8e80-93a6b2765bcb",
    "6ed357d8-79f2-46eb-921b-7744c6e53a99"
  ]
}

###

GET http://localhost:3000/companies/3f89b7b2-d0e8-4d9e-bc4e-4c88709c1e76/rank?view=revenueAsc

