GET http://localhost:3000/companies

###

GET http://localhost:3000/companies?search=코드잇&offset=0&limit=10&view=employeeDesc

###

GET http://localhost:3000/companies/3f89b7b2-d0e8-4d9e-bc4e-4c88709c1e76

