GET http://localhost:3000/companies

###

GET http://localhost:3000/companies?search=코드잇&offset=0&limit=10&view=employeeDesc

###

GET http://localhost:3000/companies/bb3c32fd-286c-4225-aa7c-78b42f320184

###

POST http://localhost:3000/companies/bb3c32fd-286c-4225-aa7c-78b42f320184/comparison?view=revenueDesc
Content-Type: application/json

{
  "bodyCompanyIds" : [
    "c1bc22e7-6e01-4b4d-85f6-63804920f157",
    "bc93bbb0-9443-497f-a2d6-2dbe52448485",
    "c4c38c7d-c6c5-47e0-a364-0f30fa0e585a"
  ]
}

###

GET http://localhost:3000/companies/bb3c32fd-286c-4225-aa7c-78b42f320184/rank?view=revenueAsc

