POST http://localhost:3000/investments
Content-Type: application/json

{
  "name": "김연우",
  "companyId": "d1f9c0a8-251e-469d-9b8c-1e6e84f1de21",
  "amount": 3000,
  "comment": "투자할 가치가 있습니다.",
  "password": "test1111"
}

###

GET http://localhost:3000/investments?view=simInvestAsc&offset=0&limit=10

###

GET http://localhost:3000/investments/d1f9c0a8-251e-469d-9b8c-1e6e84f1de21

###

PATCH  http://localhost:3000/investments/2b77f724-d682-43aa-850e-7a960be569b9
Content-Type: application/json

{
  "amount": 5000
}

###

DELETE http://localhost:3000/investments/8f3a9c17-fed5-4deb-9b81-d34034749bec

###

POST http://localhost:3000/investments/7cdb2b3c-8cef-4323-83a0-e54e7d2169ad/userCheck
Content-Type: application/json

{
  "password": "test1111"
}
