GET http://localhost:3000/selections?view=mySelectionDesc&limit=10&offset=0

### 
POST http://localhost:3000/selections/bb3c32fd-286c-4225-aa7c-78b42f320184/my-company/select

###

POST http://localhost:3000/selections/bb3c32fd-286c-4225-aa7c-78b42f320184/my-company/cancel

### 
POST http://localhost:3000/selections/bb3c32fd-286c-4225-aa7c-78b42f320184/compared-company/select

###

POST http://localhost:3000/selections/bb3c32fd-286c-4225-aa7c-78b42f320184/compared-company/cancel

