GET http://localhost:3000/selections

### 
GET http://localhost:3000/selections?view=mySelectionDesc&limit=10&offset=0

### 
POST http://localhost:3000/selections/d1f9c0a8-251e-469d-9b8c-1e6e84f1de21/my-company
